summary: XML-based font configuration library
web-url: https://wiki.freedesktop.org/www/Software/fontconfig
git-url: https://gitlab.freedesktop.org/fontconfig/fontconfig
src-url: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.17.1/fontconfig-2.17.1.tar.gz
src-sha: 82e73b26adad651b236e5f5d4b3074daf8ff0910188808496326bd3449e5261d
license: MIT
dep-pkg: libfreetype libexpat libiconv
dep-upp: gperf python3

install: |
    mesonw \
        -Dnls=disabled \
        -Diconv=enabled \
        -Dtests=disabled \
        -Dtools=disabled
